# TCL File Generated by Component Editor 12.1sp1
# Sun Mar 16 18:22:04 MDT 2014
# DO NOT MODIFY


# 
# i2c_opencores "i2c_opencores" v1.0
# null 2014.03.16.18:22:04
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module i2c_opencores
# 
set_module_property NAME i2c_opencores
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME i2c_opencores
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_master_byte_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_master_defines.v VERILOG PATH db/ip/system/submodules/i2c_master_defines.v
add_fileset_file i2c_master_top.v VERILOG PATH db/ip/system/submodules/i2c_master_top.v
add_fileset_file timescale.v VERILOG PATH db/ip/system/submodules/timescale.v
add_fileset_file i2c_opencores.v VERILOG PATH db/ip/system/submodules/i2c_opencores.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG PATH db/ip/system/submodules/i2c_master_byte_ctrl.v


# 
# parameters
# 
add_parameter ST_IDLE STD_LOGIC_VECTOR 0
set_parameter_property ST_IDLE DEFAULT_VALUE 0
set_parameter_property ST_IDLE DISPLAY_NAME ST_IDLE
set_parameter_property ST_IDLE WIDTH 6
set_parameter_property ST_IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property ST_IDLE UNITS None
set_parameter_property ST_IDLE ALLOWED_RANGES 0:63
set_parameter_property ST_IDLE HDL_PARAMETER true
add_parameter ST_START STD_LOGIC_VECTOR 1
set_parameter_property ST_START DEFAULT_VALUE 1
set_parameter_property ST_START DISPLAY_NAME ST_START
set_parameter_property ST_START WIDTH 6
set_parameter_property ST_START TYPE STD_LOGIC_VECTOR
set_parameter_property ST_START UNITS None
set_parameter_property ST_START ALLOWED_RANGES 0:63
set_parameter_property ST_START HDL_PARAMETER true
add_parameter ST_READ STD_LOGIC_VECTOR 2
set_parameter_property ST_READ DEFAULT_VALUE 2
set_parameter_property ST_READ DISPLAY_NAME ST_READ
set_parameter_property ST_READ WIDTH 6
set_parameter_property ST_READ TYPE STD_LOGIC_VECTOR
set_parameter_property ST_READ UNITS None
set_parameter_property ST_READ ALLOWED_RANGES 0:63
set_parameter_property ST_READ HDL_PARAMETER true
add_parameter ST_WRITE STD_LOGIC_VECTOR 4
set_parameter_property ST_WRITE DEFAULT_VALUE 4
set_parameter_property ST_WRITE DISPLAY_NAME ST_WRITE
set_parameter_property ST_WRITE WIDTH 6
set_parameter_property ST_WRITE TYPE STD_LOGIC_VECTOR
set_parameter_property ST_WRITE UNITS None
set_parameter_property ST_WRITE ALLOWED_RANGES 0:63
set_parameter_property ST_WRITE HDL_PARAMETER true
add_parameter ST_ACK STD_LOGIC_VECTOR 8
set_parameter_property ST_ACK DEFAULT_VALUE 8
set_parameter_property ST_ACK DISPLAY_NAME ST_ACK
set_parameter_property ST_ACK WIDTH 6
set_parameter_property ST_ACK TYPE STD_LOGIC_VECTOR
set_parameter_property ST_ACK UNITS None
set_parameter_property ST_ACK ALLOWED_RANGES 0:63
set_parameter_property ST_ACK HDL_PARAMETER true
add_parameter ST_STOP STD_LOGIC_VECTOR 16
set_parameter_property ST_STOP DEFAULT_VALUE 16
set_parameter_property ST_STOP DISPLAY_NAME ST_STOP
set_parameter_property ST_STOP WIDTH 6
set_parameter_property ST_STOP TYPE STD_LOGIC_VECTOR
set_parameter_property ST_STOP UNITS None
set_parameter_property ST_STOP ALLOWED_RANGES 0:63
set_parameter_property ST_STOP HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point avalon_tristate_slave
# 
add_interface avalon_tristate_slave avalon_tristate end
set_interface_property avalon_tristate_slave activeCSThroughReadLatency false
set_interface_property avalon_tristate_slave associatedClock ""
set_interface_property avalon_tristate_slave explicitAddressSpan 0
set_interface_property avalon_tristate_slave holdTime 0
set_interface_property avalon_tristate_slave isMemoryDevice false
set_interface_property avalon_tristate_slave isNonVolatileStorage false
set_interface_property avalon_tristate_slave maximumPendingReadTransactions 0
set_interface_property avalon_tristate_slave printableDevice false
set_interface_property avalon_tristate_slave readLatency 0
set_interface_property avalon_tristate_slave readWaitTime 1
set_interface_property avalon_tristate_slave setupTime 0
set_interface_property avalon_tristate_slave timingUnits Cycles
set_interface_property avalon_tristate_slave writeWaitTime 0
set_interface_property avalon_tristate_slave ENABLED true

add_interface_port avalon_tristate_slave rst resetrequest_n Input 1
add_interface_port avalon_tristate_slave nReset beginbursttransfer_n Input 1
add_interface_port avalon_tristate_slave clk_cnt writebyteenable_n Input 16
add_interface_port avalon_tristate_slave ena beginbursttransfer_n Input 1
add_interface_port avalon_tristate_slave cmd_ack readdatavalid_n Output 1
add_interface_port avalon_tristate_slave din beginbursttransfer_n Input 8
add_interface_port avalon_tristate_slave dout readdatavalid_n Output 8
add_interface_port avalon_tristate_slave scl_i beginbursttransfer_n Input 1
add_interface_port avalon_tristate_slave scl_o readdatavalid_n Output 1
add_interface_port avalon_tristate_slave scl_oen readdatavalid_n Output 1
add_interface_port avalon_tristate_slave sda_i beginbursttransfer_n Input 1
add_interface_port avalon_tristate_slave sda_o readdatavalid_n Output 1
add_interface_port avalon_tristate_slave sda_oen readdatavalid_n Output 1
add_interface_port avalon_tristate_slave start beginbursttransfer_n Input 1
add_interface_port avalon_tristate_slave stop beginbursttransfer_n Input 1
add_interface_port avalon_tristate_slave read read Input 1
add_interface_port avalon_tristate_slave write write Input 1
add_interface_port avalon_tristate_slave ack_in beginbursttransfer_n Input 1
add_interface_port avalon_tristate_slave ack_out readdatavalid_n Output 1
add_interface_port avalon_tristate_slave i2c_busy readdatavalid_n Output 1
add_interface_port avalon_tristate_slave i2c_al readdatavalid_n Output 1
set_interface_assignment avalon_tristate_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_tristate_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_tristate_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_tristate_slave embeddedsw.configuration.isPrintableDevice 0

